---
collections_dir: collections
collections:
  dnd5e_boons:
    output: false
    sort_by: slug
  adventures:
    output: false
    sort_by: campaign_index
  campaigns:
    output: false
    sort_by: slug
  characters:
    output: false
    sort_by: slug
  locations:
    output: false
    sort_by: slug
  organizations:
    output: false
    sort_by: slug
  scenes:
    output: false
    sort_by: slug
defaults:
- scope:
    path: ''
    type: 'pages'
  values:
    encoding: 'utf-8'
    layout: 'page'
    title: 'Incunabulum'
exclude:
  - .git
  - Gemfile
  - Gemfile.lock
  - README.md
  - Rakefile
  - /vendor
  - tasks.thor
markdown: kramdown
repository: sleepingkingstudios/incunabulum
theme: jekyll-theme-primer
title: Incunabulum
description: A repository of game design and development for Sleeping King Studios.
github: false
